apiVersion : apps/v1
kind: Deployment
metadata:
  name: zccstreamiltdocker 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zccstreamiltdocker
  template:
    metadata:
      labels:
        app: zccstreamiltdocker 
    spec:
      containers:
        - name: zccstreamiltdocker 
          image: dockertestzcc.azurecr.io/zccstreamiltdocker
          volumeMounts: 
        - 
          mountPath: /etc/keys_azure
          name: keyb
          readOnly: true
          ports:
          - containerPort: 8501
      volumes: 
        - 
          name: keyb
          secret: 
            secretName: mysecret2
#           env:
#             - name: KEY_BLOB
#               valueFrom:
#                 secretKeyRef:
#                   name: mysecret2
#                   key: keyblob
